# Generated by Django 5.1.6 on 2025-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tg_nick",
        ),
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм сhat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграм сhat-id",
            ),
        ),
    ]
