# Generated by Django 5.1.6 on 2025-02-12 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pleasanthabit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pleasant_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите связанную привычку",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.pleasanthabit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="usefulhabit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите пользователя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="useful_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
